"""render_research_docs.py -- render every research document to self-contained HTML.

WHY A GENERATOR AND NOT 21 HAND-WRITTEN PAGES. The project's own convention is one source of truth. If the
research documents are edited as markdown and the HTML is a second, hand-maintained copy, the two drift and the
drift is invisible until someone quotes the wrong one. So: markdown stays the source, HTML is generated, and the
generator is the only thing that knows the layout.

WHAT IT PRODUCES
  html/index.html          -- the document set: what exists, what it is for, its status, its source
  html/<slug>.html         -- one page per source document, shared stylesheet, breadcrumb back to the index

Every page states its source path and the generator's run time, so a reader can always tell a generated view
from an authored original.

Run: python tools/render_research_docs.py
"""
import html as html_mod
import json
import re
import time
from pathlib import Path

from markdown_it import MarkdownIt

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "html"
OUT.mkdir(exist_ok=True)

md = MarkdownIt("commonmark", {"html": True, "linkify": False}).enable("table").enable("strikethrough")

# ---- the manifest: every research-relevant document, grouped by what it is for ------------------
# status: frozen = pre-registered / immutable; current = maintained; superseded = kept for the record
MANIFEST = [
    ("Research output", [
        ("figures/out/Fig_learning_curve.png", "figure", "Figure 1: the compute axis saturates",
         "current", "Specification curve against the measured noise floor and the decision threshold."),
        ("figures/out/Fig_mechanism.png", "figure", "Figure 2: where the advantage comes from",
         "current", "Accuracy by teacher self-agreement, and the concentration of the gain against the item share."),
        ("figures/out/Fig_C1_arms.png", "figure", "Extended Data Figure 1: the arms and their chance floors",
         "current", "Generated by figures/fig_c1_arms.py; layout audited by figures/fig_qc.py."),
        ("figures/out/Fig_floor_B.png", "figure", "Extended Data Figure 2: Floor B and the threshold budget",
         "current", "Generated by figures/fig_floor_B.py; layout audited by figures/fig_qc.py."),
        ("figures/out/Fig_hillclimb.png", "figure", "Hill-climb: naive chain vs threshold-gated chain",
         "current", "Generated by figures/fig_hillclimb.py; produced with MOCK data to validate layout only."),
        ("figures/out/Fig_hillclimb_progress.png", "figure", "Progress trajectory over generations",
         "current", "Generated by figures/fig_hillclimb_progress.py."),
        ("lean/JevRSI/AcceptRule.lean", "formal", "Lean 4: the statistical core of the accept rule", "current",
         "Four closed theorems, no sorry. Toolchain Lean v4.34.1 + Mathlib v4.34.1."),
    ]),
    ("Pre-registration and governing rules", [
        ("docs/JevRSI_global_principles_v1.md", "governing", "The seven global rules and the container's framework",
         "current", "Rule [7] deliverable. Also carries the harness boundary: borrow the framework, not the findings."),
        ("docs/JevRSI_preregistration.md", "frozen", "Pre-registration", "frozen",
         "Immutable protocol: steps, batch, grad-accum, learning rates, selection metric."),
        ("CURRENT_OBJECT.md", "governing", "Single source of truth for what the object is", "current",
         "Defines the current object and enforces the retired-object boundary."),
    ]),
    ("Analyses", [
        ("docs/JevRSI_target_backward_derivation.md", "analysis", "Target derived backwards from the metric's meaning",
         "current", "Reference points, the meaning-boundary revision, the completed learning curve. Its "
         "ceiling reading is superseded by RESEARCH_GOAL_v2."),
        ("docs/JevRSI_goal_feasibility_2026-09-28.md", "analysis", "Goal feasibility", "current",
         "Rule-by-rule verdict, storage arithmetic with its correction, the Lean scope tension."),
        ("docs/JevRSI_decision_record_2026-09-28.md", "analysis", "Decision record D1-D5", "current",
         "Five decisions with the evidence that forces each."),
        ("docs/JevRSI_starting_point_review_2026-09-28.md", "analysis", "Starting-point review", "current",
         "What the substrate is, priced honestly; the 2.95x capacity confound."),
        ("docs/JevRSI_pipeline_audit_2026-09-28.md", "analysis", "Independent pipeline audit", "current",
         "Structural review of the pipeline; runs as a preflight gate."),
        ("measurement/floor_b_host_capacity.md", "analysis", "Host capacity", "current",
         "Where the 12 GB card fails; measured rather than estimated."),
        ("docs/evidence/frontier_comparison_2026-09-28.json", "analysis",
         "Frontier comparison (machine-readable)", "current",
         "Delegated, source-verified: six arXiv ids confirmed, ten further precedents found."),
    ]),
    ("Operations", [
        ("docs/DOCUMENT_MAP.md", "ops", "Document map", "current", "Where everything lives."),
        ("docs/JevRSI_handoff_2026-09-27.md", "ops", "Handoff 2026-09-27", "current",
         "Session handoff note."),
        ("docs/incident_2026-09-25_tree_loss.md", "ops", "Incident record", "frozen",
         "A tree-loss incident, kept because the failure class recurs."),
        ("README.md", "ops", "Repository readme", "current", "Entry point."),
    ]),
]

CSS = """
:root{--ink:#141414;--mut:#5d5d5d;--rule:#d8d8d8;--accent:#7a1f1f;--bg:#fdfdfb;--code:#f2f1ee}
*{box-sizing:border-box}
body{margin:0 auto;max-width:52rem;padding:2.6rem 1.6rem 6rem;background:var(--bg);color:var(--ink);
     font-family:"Iowan Old Style","Palatino Linotype",Palatino,Georgia,serif;line-height:1.62;font-size:16px}
nav.crumb{font-family:-apple-system,"Segoe UI",Roboto,sans-serif;font-size:.8rem;color:var(--mut);
          border-bottom:1px solid var(--rule);padding-bottom:.6rem;margin-bottom:1.6rem}
nav.crumb a{color:var(--accent);text-decoration:none}
h1{font-size:1.6rem;line-height:1.3;margin:0 0 .4rem;font-weight:600;letter-spacing:-.01em}
h2{font-size:1.14rem;margin:2.3rem 0 .6rem;font-weight:600;border-bottom:1px solid var(--rule);padding-bottom:.25rem}
h3{font-size:1rem;margin:1.6rem 0 .4rem;font-weight:600}
h4{font-size:.94rem;margin:1.2rem 0 .3rem;font-weight:600;color:#333}
p{margin:.7rem 0}
ul,ol{margin:.6rem 0 .9rem;padding-left:1.4rem}
li{margin:.25rem 0}
code{font-family:"SF Mono",Menlo,Consolas,monospace;font-size:.85em;background:var(--code);padding:.08em .3em;border-radius:2px}
pre{background:var(--code);border:1px solid var(--rule);border-radius:3px;padding:.8rem 1rem;overflow-x:auto;
    font-size:.82rem;line-height:1.5}
pre code{background:none;padding:0}
blockquote{margin:1.1rem 0;padding:.5rem 0 .5rem 1rem;border-left:3px solid var(--accent);color:#333}
table{border-collapse:collapse;width:100%;margin:1rem 0 1.3rem;font-size:.87rem;
      font-family:-apple-system,"Segoe UI",Roboto,sans-serif}
th,td{text-align:left;padding:.4rem .55rem;border-bottom:1px solid var(--rule);vertical-align:top}
th{font-weight:600;border-bottom:1.5px solid #b9b9b9}
img{max-width:100%;height:auto;border:1px solid var(--rule);border-radius:3px;margin:.6rem 0}
hr{border:none;border-top:1px solid var(--rule);margin:2.2rem 0}
a{color:var(--accent)}
.meta{font-size:.8rem;color:var(--mut);font-family:-apple-system,"Segoe UI",Roboto,sans-serif;
      border-left:3px solid var(--rule);padding-left:.8rem;margin:1.2rem 0 2rem}
.badge{font-family:-apple-system,"Segoe UI",Roboto,sans-serif;font-size:.7rem;padding:.12em .5em;border-radius:2px;
       background:#eee;color:#444;white-space:nowrap}
.badge.frozen{background:#e6ecf5;color:#274b7a}
.badge.current{background:#e2efe2;color:#245a24}
.tag{font-family:-apple-system,"Segoe UI",Roboto,sans-serif;font-size:.72rem;color:var(--mut)}
footer{margin-top:3.4rem;padding-top:1rem;border-top:1px solid var(--rule);font-size:.78rem;color:var(--mut)}
"""

TEMPLATE = """<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>{title}</title>
<style>{css}</style></head><body>
<nav class="crumb"><a href="index.html">Research documents</a> &nbsp;›&nbsp; {category}</nav>
<h1>{title}</h1>
<div class="meta"><span class="badge {status}">{status}</span> &nbsp; {desc}<br>
Generated from <code>{source}</code> by <code>tools/render_research_docs.py</code> at {stamp}.
The markdown source is authoritative; this page is a rendered view of it.</div>
{body}
<footer>JevRSI research document set · {stamp}</footer>
</body></html>
"""


def slug(p: str) -> str:
    p = re.sub(r"[^A-Za-z0-9]+", "-", p).strip("-").lower()
    return p[:110] or "doc"


def strip_leading_h1(text: str) -> str:
    """Drop the source's own H1: the template already renders the title."""
    return re.sub(r"^\s*#\s+.*?\n", "", text, count=1)


def render_md(text: str) -> str:
    body = md.render(strip_leading_h1(text))
    # inline a figure when the source links a local image
    body = body.replace('src="figures/', 'src="../figures/')
    return body


stamp = time.strftime("%Y-%m-%d %H:%M")
rows, rendered, missing = [], 0, []

for category, docs in MANIFEST:
    for rel, kind, title, status, desc in docs:
        src = REPO / rel
        if not src.exists():
            missing.append(rel)
            continue
        out_name = slug(rel) + ".html"
        if kind == "figure":
            body = (f'<img src="../{rel}" alt="{html_mod.escape(title)}">'
                    f'<p class="tag">Source image: <code>{rel}</code></p>')
            out_name = slug(rel) + ".html"
        elif src.suffix == ".md":
            body = render_md(src.read_text(encoding="utf-8", errors="replace"))
        elif src.suffix == ".html":
            # an authored HTML document is linked, never re-rendered into a second copy
            body = (f'<p>This document is authored HTML and is served from its own file: '
                    f'<a href="../{rel}">{rel}</a>.</p>')
        elif src.suffix == ".json":
            try:
                pretty = json.dumps(json.loads(src.read_text(encoding="utf-8")), indent=2,
                                    ensure_ascii=False)
            except Exception:
                pretty = src.read_text(encoding="utf-8", errors="replace")
            body = f"<pre><code>{html_mod.escape(pretty[:120000])}</code></pre>"
        else:
            body = (f"<pre><code>{html_mod.escape(src.read_text(encoding='utf-8', errors='replace')[:120000])}"
                    f"</code></pre>")
        (OUT / out_name).write_text(
            TEMPLATE.format(title=html_mod.escape(title), css=CSS, category=category,
                            status=status, desc=html_mod.escape(desc),
                            source=rel, stamp=stamp, body=body),
            encoding="utf-8")
        rendered += 1
        rows.append((category, kind, title, status, desc, rel, out_name))

# ---- the index ------------------------------------------------------------------------------------
secs = []
cur = None
for category, kind, title, status, desc, rel, out_name in rows:
    if category != cur:
        if cur is not None:
            secs.append("</table>")
        secs.append(f"<h2>{category}</h2>")
        secs.append('<table><thead><tr><th>Document</th><th>Status</th><th>What it is</th>'
                    '<th>Source</th></tr></thead><tbody>')
        cur = category
    link = f'<a href="{out_name}">{html_mod.escape(title)}</a>'
    if kind == "figure":
        link = f'<a href="{out_name}">{html_mod.escape(title)}</a> <span class="tag">(figure)</span>'
    secs.append(f'<tr><td>{link}</td><td><span class="badge {status}">{status}</span></td>'
                f'<td>{html_mod.escape(desc)}</td><td><code>{rel}</code></td></tr>')
secs.append("</table>")

index_body = f"""
<p><strong>{rendered} research documents</strong>, grouped by what each is for. Every page is generated from a
markdown or JSON source that remains authoritative; the HTML is a rendered view, never a second copy to maintain.
Pre-registered documents are marked <span class="badge frozen">frozen</span> and must not be edited after
execution — amendments are appended, not rewritten.</p>
{''.join(secs)}
<h2>Not included, and why</h2>
<p>Documents under <code>archive/</code> belong to research lines that have been retired or superseded; they are
kept for the historical record and are deliberately absent from this set. Working notes that describe process
rather than research — session handoffs, incident records — are included only where they carry a finding worth
citing.</p>
"""
(OUT / "index.html").write_text(
    TEMPLATE.format(title="JevRSI research document set", css=CSS, category="index",
                    status="current", desc=f"Inventory of the research-relevant documents ({rendered} pages).",
                    source="tools/render_research_docs.py", stamp=stamp, body=index_body),
    encoding="utf-8")

print(f"rendered {rendered} documents into {OUT}")
if missing:
    print(f"[WARN] {len(missing)} manifest entr(y/ies) not found on disk:")
    for m in missing:
        print(f"    - {m}")
print(f"  index: {OUT / 'index.html'}")
